---
name: Environment information
description: Provides basic information about a environemnt

inputs:
  environment:
    required: true
    description: The name of the environemnt to check.

outputs:
  exists:
    description: '`true` if a enviromment for the given name exists.'
    value: ${{ steps.result.outputs.exists }}


runs:
  using: composite
  steps:
    - name: Query GitHub API
      shell: bash
      run: >-
        gh api
        -H "Accept: application/vnd.github+json"
        -H "X-GitHub-Api-Version: 2022-11-28"
        "/repos/{owner}/{repo}/environments/${{ inputs.environment }}"
        2>error >output | true

    - name: Evaluate
      if: ${{ failure() || success() }}
      id: result
      shell: bash
      run: >-
        if [ -s error ]; then
          echo "exists=false" >> "$GITHUB_OUTPUT"
        else
          echo "exists=true" >> "$GITHUB_OUTPUT"
        fi
