---
name: Check
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  checks: write
  contents: read
  issues: read
  packages: read
  pull-requests: write
  statuses: write

jobs:
  test:
    env:
      GH_REPO: paulschuberth/environments-action
      GH_TOKEN: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        name: Positive example
        id: example-one
        with:
          environment: example

      - name: Assert positive example
        if: ${{ steps.example-one.outputs.exists != 'true' }}
        shell: bash
        run: exit 1

      - uses: ./
        name: Negative example
        continue-on-error: true
        id: example-two
        with:
          environment: non-existant

      - name: Assert negative example
        if: ${{ steps.example-two.outputs.exists != 'false' }}
        shell: bash
        run: exit 1


  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review
          fail_on_error: true
          filter_mode: nofilter

      - name: Lint
        uses: github/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GENERATED_FILES: true
          IGNORE_GITIGNORED_FILES: true
